# ----
# Site

title: "Wenhan's Resume"
url: "https://notefun.github.io/resumes"

# ---
# Author

author:
  avatar       : "/images/profile.png" 
  googlescholar: "https://scholar.google.com/citations?user=NBSeJLkAAAAJ&hl=en&oi=sra"
  github       : "ivyee17"
  linkedin     : "https://www.linkedin.cn/injobs/in/wu-wenhan-52453a206"
  gitee        : "wenhan17" ## self-defined val!! not compat with academic-page sidebar!

slogen: "Life is not a check-list of acquisition or achievement. Your qualifications, your CV, are not your life. Life is difficult, and complicated, and beyond anyone’s total control, and the humility to know that will enable you to survive its vicissitudes."


# -----
# Build

Timezone: Etc/UTC

collections:
  resumes:
    output: true
    permalink: /resumes/:categories/:title/
  
paginate: 10
permalink: pretty


# ---
# Jekyll Config

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

sass:
  sass_dir: .
  style: compressed
